services:
  app:
    image: maxthemerman/stingray-landing:prod
    network_mode: host
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Health check to ensure the service is running properly
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s