version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev.alternative
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    command: npm start
    # Try to avoid network issues during build
    network_mode: bridge