version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    command: npm start